<!-- DO NOT EDIT THIS FILE-->
<!-- IF YOU EDIT THIS FILE, YOU WILL BE KICKED OUT OF THE INTERNSHIP-->

<html>
   <?php include 'partials/header.php';?>
   <body class=" pi">
      <?php include 'partials/navbar.php';?>
      <section class="main-section">
         <div class="container">
            <div class="row">
               <div class="col-md-12 col-sm-6 col-xs-12">
                  <div class="col-md-6 col-xs-12">
                     <div class="intern-block border-blue">
                        <img src="https://res.cloudinary.com/topebush/image/upload/v1554568662/20150413000641.jpg" alt="Mark Essien">
                        <h6>Temitope Charles</h6>
                        <p>Software Developer</p>
                        <ul class="list">
                           <li><a href="#" target="_blank"<i class="fab fa-twitter fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-github fa-2x"></i></a></li>
                           <li><a href="#" target="_blank"<i class="fab fa-medium fa-2x"></i></a></li>
                        </ul>
                     </div>
                  </div>
                  <div class="col-md-6 col-xs-12 align-items-center">
                     <div class="intern-bio border-blue">
                        <h6>About me</h6>
                        <p> I am a software developer who loves to work on exciting projects, I work my magic using Javascript and sometimes Python. When i'm not coding, I'm watching football </p>
                        <br />
                        <h6>Skills</h6>
                        <p>JavaScript | Python | Content Developer</p>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         </div>
      </section>
   </body>
   <?php include 'partials/footer.php';?>
</html>
